In [1]:
from csv import reader #Package that reads the csv file.

with open('./data/ai_startup_funding_database_2014_2025.csv', encoding="utf-8") as opened_file:
    read_file = reader(opened_file)
    data_list = list(read_file) # This stores the data in the list of lists format.

In [2]:
data_list

[['company',
  'deal_date',
  'round_type',
  'amount_usd_millions',
  'pre_money_valuation_millions',
  'post_money_valuation_millions',
  'lead_investors',
  'other_investors',
  'sector',
  'subsector',
  'hq_city',
  'hq_country',
  'founded_year',
  'ceo',
  'employees_approx',
  'annual_revenue_millions',
  'profitable',
  'ipo_status',
  'key_products',
  'open_source',
  'source',
  'year',
  'quarter',
  'month',
  'deal_size_tier',
  'is_us_company',
  'stage_number'],
 ['DeepMind',
  '2014-01-26',
  'Acquisition',
  '500',
  '',
  '',
  'Google (acquirer)',
  'N/A',
  'Foundation Model / Research',
  'AI Research Lab',
  'London',
  'United Kingdom',
  '2010',
  'Demis Hassabis',
  '400',
  '',
  'False',
  'Acquired by Google',
  'AlphaFold, Gemini, AlphaGo',
  'True',
  'The Information, Google',
  '2014',
  '1',
  '1',
  'Large ($500M+)',
  'False',
  '0'],
 ['OpenAI',
  '2019-07-22',
  'Strategic Investment',
  '1000',
  '',
  '',
  'Microsoft',
  'None disclosed',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'San Francisco',
  'United States',
  '2015',
  'Sam Altman',
  '120',
  '',
  'False',
  'Private',
  'GPT-2, OpenAI Five',
  'True',
  'Microsoft blog',
  '2019',
  '3',
  '7',
  'Unicorn ($1B+)',
  'True',
  '8'],
 ['Palantir',
  '2020-09-30',
  'Direct Listing',
  '0',
  '',
  '15800.0',
  'Public Market (NYSE)',
  'N/A',
  'AI Application',
  'Data Analytics / Defense AI',
  'Denver',
  'United States',
  '2003',
  'Alex Karp',
  '2400',
  '1093.0',
  'True',
  'Public (NYSE: PLTR)',
  'Foundry, Gotham, AIP',
  'False',
  'SEC filing',
  '2020',
  '3',
  '9',
  'Early (<$100M)',
  'True',
  '10'],
 ['UiPath',
  '2021-04-21',
  'IPO',
  '1340',
  '',
  '35800.0',
  'Public Market (NYSE)',
  'Morgan Stanley, JPMorgan, BofA',
  'AI Application',
  'Robotic Process Automation',
  'New York',
  'United States',
  '2005',
  'Daniel Dines',
  '4000',
  '892.0',
  'False',
  'Public (NYSE: PATH)',
  'UiPath Platform, AI Center',
  'False',
  'SEC S-1 filing',
  '2021',
  '2',
  '4',
  'Unicorn ($1B+)',
  'True',
  '10'],
 ['SenseTime',
  '2021-12-20',
  'IPO',
  '740',
  '',
  '16800.0',
  'Public Market (HKEX)',
  'Cornerstone: CITIC, CICC, HAO Capital',
  'AI Application',
  'Computer Vision / Smart City',
  'Hong Kong',
  'China',
  '2014',
  'Xu Li',
  '6000',
  '700.0',
  'False',
  'Public (HKEX: 0020)',
  'SenseCore, facial recognition, autonomous driving',
  'False',
  'HKEX filings',
  '2021',
  '4',
  '12',
  'Large ($500M+)',
  'False',
  '10'],
 ['OpenAI',
  '2022-04-01',
  'Series D',
  '300',
  '19700.0',
  '20000.0',
  'Tiger Global, a16z',
  'Sequoia Capital, Bedrock',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'San Francisco',
  'United States',
  '2015',
  'Sam Altman',
  '375',
  '36.0',
  'False',
  'Private',
  'GPT-3, DALL-E 2, Codex',
  'False',
  'WSJ, PitchBook',
  '2022',
  '2',
  '4',
  'Growth ($100M+)',
  'True',
  '5'],
 ['Adept AI',
  '2022-04-26',
  'Series A',
  '65',
  '935.0',
  '1000.0',
  'Greylock Partners',
  'Addition, Atlassian Ventures',
  'AI Application',
  'AI Agent / Action Models',
  'San Francisco',
  'United States',
  '2022',
  'David Luan',
  '40',
  '',
  'False',
  'Acqui-hired by Amazon 2024',
  'ACT-1 action model',
  'False',
  'TechCrunch, The Information',
  '2022',
  '2',
  '4',
  'Early (<$100M)',
  'True',
  '2'],
 ['Stability AI',
  '2022-10-17',
  'Seed',
  '101',
  '900.0',
  '1000.0',
  'Lightspeed, Coatue',
  "O'Shaughnessy Ventures",
  'Foundation Model / Image Gen',
  'Image Generation',
  'London',
  'United Kingdom',
  '2019',
  'Emad Mostaque (resigned 2024)',
  '150',
  '11.0',
  'False',
  'Private (struggling)',
  'Stable Diffusion',
  'True',
  'Bloomberg, TechCrunch',
  '2022',
  '4',
  '10',
  'Growth ($100M+)',
  'False',
  '1'],
 ['OpenAI',
  '2023-01-23',
  'Strategic Investment',
  '10000',
  '19000.0',
  '29000.0',
  'Microsoft',
  'None disclosed',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'San Francisco',
  'United States',
  '2015',
  'Sam Altman',
  '770',
  '1600.0',
  'False',
  'Private',
  'ChatGPT, GPT-4, DALL-E 2',
  'False',
  'Microsoft blog, WSJ',
  '2023',
  '1',
  '1',
  'Mega ($10B+)',
  'True',
  '8'],
 ['Cohere',
  '2023-06-08',
  'Series C',
  '270',
  '1930.0',
  '2200.0',
  'Inovia Capital',
  'Nvidia, Oracle, Salesforce Ventures, Index Ventures',
  'Foundation Model / LLM',
  'Enterprise AI',
  'Toronto',
  'Canada',
  '2019',
  'Aidan Gomez',
  '450',
  '35.0',
  'False',
  'Private',
  'Command, Embed, Rerank',
  'True',
  'TechCrunch',
  '2023',
  '2',
  '6',
  'Growth ($100M+)',
  'False',
  '4'],
 ['Inflection AI',
  '2023-06-29',
  'Series B',
  '1300',
  '2700.0',
  '4000.0',
  'Microsoft, Nvidia, Reid Hoffman',
  'Bill Gates, Eric Schmidt, Greylock',
  'Foundation Model / LLM',
  'Personal AI Assistant',
  'Palo Alto',
  'United States',
  '2022',
  'Mustafa Suleyman (left for Microsoft)',
  '200',
  '',
  'False',
  'Effectively Acquired by Microsoft',
  'Pi personal AI (wound down)',
  'False',
  'NYT, Bloomberg',
  '2023',
  '2',
  '6',
  'Unicorn ($1B+)',
  'True',
  '3'],
 ['Hugging Face',
  '2023-08-24',
  'Series D',
  '235',
  '4265.0',
  '4500.0',
  'Google, Amazon, Nvidia',
  'Salesforce, AMD, Intel, IBM, Qualcomm',
  'AI Infrastructure',
  'Open Source AI Platform',
  'New York',
  'United States',
  '2016',
  'Clem Delangue',
  '250',
  '70.0',
  'False',
  'Private',
  'Hugging Face Hub, Transformers, Inference API',
  'True',
  'TechCrunch, Hugging Face blog',
  '2023',
  '3',
  '8',
  'Growth ($100M+)',
  'True',
  '5'],
 ['Anthropic',
  '2023-09-25',
  'Strategic Investment',
  '4000',
  '',
  '',
  'Amazon',
  'None disclosed',
  'Foundation Model / LLM',
  'AI Safety Research',
  'San Francisco',
  'United States',
  '2021',
  'Dario Amodei',
  '500',
  '200.0',
  'False',
  'Private',
  'Claude 2, Claude API',
  'False',
  'Amazon press release, WSJ',
  '2023',
  '3',
  '9',
  'Unicorn ($1B+)',
  'True',
  '8'],
 ['Figure AI',
  '2024-02-29',
  'Series B',
  '675',
  '2000.0',
  '2600.0',
  'Microsoft, Nvidia, OpenAI Startup Fund',
  'Jeff Bezos, Intel, Samsung, Parkway Venture Capital',
  'AI Application',
  'Humanoid Robotics',
  'Sunnyvale',
  'United States',
  '2022',
  'Brett Adcock',
  '700',
  '',
  'False',
  'Private',
  'Figure 01, Figure 02 humanoid robots',
  'False',
  'Bloomberg, TechCrunch',
  '2024',
  '1',
  '2',
  'Large ($500M+)',
  'True',
  '3'],
 ['Anthropic',
  '2024-03-01',
  'Series D',
  '2750',
  '15250.0',
  '18400.0',
  'Menlo Ventures',
  'Google, Spark Capital, Salesforce Ventures',
  'Foundation Model / LLM',
  'AI Safety Research',
  'San Francisco',
  'United States',
  '2021',
  'Dario Amodei',
  '1000',
  '850.0',
  'False',
  'Private',
  'Claude 3, Claude API',
  'False',
  'TechCrunch, SEC filing',
  '2024',
  '1',
  '3',
  'Unicorn ($1B+)',
  'True',
  '5'],
 ['Wayve',
  '2024-05-07',
  'Series C',
  '1050',
  '',
  '',
  'SoftBank Vision Fund',
  'Nvidia, Microsoft, Eclipse Ventures',
  'AI Application',
  'Autonomous Driving',
  'London',
  'United Kingdom',
  '2017',
  'Alex Kendall',
  '350',
  '',
  'False',
  'Private',
  'LINGO-2, AI driving platform',
  'False',
  'TechCrunch, Financial Times',
  '2024',
  '2',
  '5',
  'Unicorn ($1B+)',
  'False',
  '4'],
 ['Mistral AI',
  '2024-06-11',
  'Series B',
  '640',
  '5400.0',
  '6000.0',
  'General Catalyst',
  'a16z, Lightspeed, BNP Paribas, Samsung',
  'Foundation Model / LLM',
  'Open-Weight AI Models',
  'Paris',
  'France',
  '2023',
  'Arthur Mensch',
  '400',
  '80.0',
  'False',
  'Private',
  'Mistral Large, Mixtral, Le Chat',
  'True',
  'TechCrunch, Les Echos',
  '2024',
  '2',
  '6',
  'Large ($500M+)',
  'False',
  '3'],
 ['Databricks',
  '2024-09-19',
  'Series I',
  '10000',
  '52000.0',
  '62000.0',
  'Thrive Capital',
  'a16z, DST Global, GIC, Iconiq',
  'AI Infrastructure',
  'Data Platform / ML Infrastructure',
  'San Francisco',
  'United States',
  '2013',
  'Ali Ghodsi',
  '6000',
  '2400.0',
  'False',
  'Private',
  'Databricks Lakehouse, Mosaic ML',
  'True',
  'Bloomberg',
  '2024',
  '3',
  '9',
  'Mega ($10B+)',
  'True',
  '9'],
 ['OpenAI',
  '2024-10-02',
  'Series E',
  '6600',
  '150000.0',
  '157000.0',
  'Thrive Capital',
  'Microsoft, Nvidia, SoftBank, Khosla Ventures, Tiger Global',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'San Francisco',
  'United States',
  '2015',
  'Sam Altman',
  '3000',
  '5400.0',
  'False',
  'Private',
  'ChatGPT, GPT-4, DALL-E 3, Sora',
  'False',
  'SEC filing, TechCrunch',
  '2024',
  '4',
  '10',
  'Unicorn ($1B+)',
  'True',
  '6'],
 ['CoreWeave',
  '2024-11-21',
  'Series C',
  '650',
  '22350.0',
  '23000.0',
  'Jane Street Capital',
  'Fidelity, Coatue, Magnetar',
  'AI Infrastructure',
  'GPU Cloud Computing',
  'Roseland',
  'United States',
  '2017',
  'Michael Intrator',
  '1300',
  '1900.0',
  'False',
  'IPO March 2025 (CRWV)',
  'GPU cloud, AI training clusters',
  'False',
  'Bloomberg, Crunchbase',
  '2024',
  '4',
  '11',
  'Large ($500M+)',
  'True',
  '4'],
 ['xAI',
  '2024-12-23',
  'Series C',
  '6000',
  '39000.0',
  '45000.0',
  'Various (undisclosed)',
  'Nvidia, A-Cap, Valor Equity Partners',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'Palo Alto',
  'United States',
  '2023',
  'Elon Musk',
  '400',
  '',
  'False',
  'Private',
  'Grok 2, Colossus',
  'True',
  'Bloomberg, SEC filing',
  '2024',
  '4',
  '12',
  'Unicorn ($1B+)',
  'True',
  '4'],
 ['Mistral AI',
  '2025-01-27',
  'Series C',
  '2000',
  '13500.0',
  '15500.0',
  'General Catalyst, Bpifrance',
  'a16z, Lightspeed, Samsung, IBM',
  'Foundation Model / LLM',
  'Open-Weight AI Models',
  'Paris',
  'France',
  '2023',
  'Arthur Mensch',
  '700',
  '300.0',
  'False',
  'Private',
  'Mistral Large 2, Codestral, Le Chat',
  'True',
  'TechCrunch, Les Echos',
  '2025',
  '1',
  '1',
  'Unicorn ($1B+)',
  'False',
  '4'],
 ['Lambda',
  '2025-02-19',
  'Series D',
  '480',
  '2000.0',
  '2500.0',
  'SGW, Andra Capital',
  'Nvidia, G Squared, ARK Invest',
  'AI Infrastructure',
  'GPU Cloud Computing',
  'San Francisco',
  'United States',
  '2012',
  'Stephen Balaban',
  '400',
  '500.0',
  'True',
  'Private',
  'Lambda Cloud, GPU clusters',
  'False',
  'TechCrunch',
  '2025',
  '1',
  '2',
  'Growth ($100M+)',
  'True',
  '5'],
 ['Together AI',
  '2025-02-20',
  'Series B',
  '305',
  '3000.0',
  '3300.0',
  'Prosperity7, General Catalyst',
  'Salesforce Ventures, Nvidia, Lux Capital',
  'AI Infrastructure',
  'Open Source AI Platform',
  'San Francisco',
  'United States',
  '2022',
  'Vipul Ved Prakash',
  '200',
  '100.0',
  'False',
  'Private',
  'Together Inference, Together Fine-Tuning',
  'True',
  'TechCrunch',
  '2025',
  '1',
  '2',
  'Growth ($100M+)',
  'True',
  '3'],
 ['Anthropic',
  '2025-03-03',
  'Series E Extension',
  '3500',
  '58000.0',
  '61500.0',
  'Lightspeed Venture Partners',
  'Salesforce Ventures, Menlo Ventures, General Catalyst',
  'Foundation Model / LLM',
  'AI Safety Research',
  'San Francisco',
  'United States',
  '2021',
  'Dario Amodei',
  '1400',
  '2800.0',
  'False',
  'Private',
  'Claude, Claude API',
  'False',
  'TechCrunch',
  '2025',
  '1',
  '3',
  'Unicorn ($1B+)',
  'True',
  '6'],
 ['Safe Superintelligence (SSI)',
  '2025-04-01',
  'Series A',
  '2000',
  '30000.0',
  '32000.0',
  'Greenoaks Capital Partners',
  'a16z, Sequoia, DST Global',
  'Foundation Model / LLM',
  'AI Safety Research',
  'Palo Alto',
  'United States',
  '2024',
  'Ilya Sutskever',
  '30',
  '',
  'False',
  'Private',
  'Safe superintelligence (stealth)',
  'False',
  'Bloomberg, Crunchbase',
  '2025',
  '2',
  '4',
  'Unicorn ($1B+)',
  'True',
  '2'],
 ['OpenAI',
  '2025-04-02',
  'Series F',
  '40000',
  '260000.0',
  '300000.0',
  'SoftBank',
  'Microsoft, Coatue, Thrive Capital',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'San Francisco',
  'United States',
  '2015',
  'Sam Altman',
  '3700',
  '11600.0',
  'False',
  'Private (IPO rumored)',
  'ChatGPT, GPT-4o, DALL-E, Sora',
  'False',
  'CNBC, Reuters, Crunchbase',
  '2025',
  '2',
  '4',
  'Mega ($10B+)',
  'True',
  '7'],
 ['Perplexity AI',
  '2025-05-01',
  'Series E',
  '500',
  '17500.0',
  '18000.0',
  'Accel',
  'IVP, Nvidia, Bezos Expeditions',
  'AI Application',
  'AI Search Engine',
  'San Francisco',
  'United States',
  '2022',
  'Aravind Srinivas',
  '250',
  '150.0',
  'False',
  'Private',
  'Perplexity Search, Perplexity Pro',
  'False',
  'Forbes, TechCrunch',
  '2025',
  '2',
  '5',
  'Large ($500M+)',
  'True',
  '6'],
 ['Ambience Healthcare',
  '2025-06-01',
  'Series C',
  '243',
  '',
  '',
  'Oak HC/FT, a16z',
  'Kleiner Perkins, OpenAI Startup Fund',
  'AI Application',
  'Healthcare AI',
  'San Francisco',
  'United States',
  '2020',
  'Mike Ng',
  '300',
  '',
  'False',
  'Private',
  'AI medical documentation, clinical AI OS',
  'False',
  'TechCrunch',
  '2025',
  '2',
  '6',
  'Growth ($100M+)',
  'True',
  '4'],
 ['Scale AI',
  '2025-06-15',
  'Strategic Investment',
  '14300',
  '14700.0',
  '29000.0',
  'Meta (49% stake)',
  'None disclosed',
  'AI Infrastructure',
  'Data Labeling / Training Data',
  'San Francisco',
  'United States',
  '2016',
  'Alexandr Wang (moved to Meta)',
  '1200',
  '1400.0',
  'False',
  'Private',
  'Data labeling, RLHF, AI infrastructure',
  'False',
  'Bloomberg, TechCrunch',
  '2025',
  '2',
  '6',
  'Mega ($10B+)',
  'True',
  '8'],
 ['xAI',
  '2025-07-15',
  'Series C',
  '10000',
  '190000.0',
  '200000.0',
  'Valor Capital, Qatar Investment Authority',
  'Kingdom Holding (Prince Al Waleed), Nvidia',
  'Foundation Model / LLM',
  'General-Purpose AI',
  'Palo Alto',
  'United States',
  '2023',
  'Elon Musk',
  '600',
  '',
  'False',
  'Private',
  'Grok, Grok 4, Colossus supercomputer',
  'True',
  'Bloomberg (Musk disputes figures)',
  '2025',
  '3',
  '7',
  'Mega ($10B+)',
  'True',
  '4'],
 ['Thinking Machines Lab',
  '2025-07-15',
  'Seed',
  '2000',
  '8000.0',
  '10000.0',
  'Andreessen Horowitz',
  'Nvidia, Accel, AMD, Cisco',
  'Foundation Model / LLM',
  'AI Research',
  'San Francisco',
  'United States',
  '2024',
  'Mira Murati',
  '30',
  '',
  'False',
  'Private',
  'Foundation models (stealth)',
  'False',
  'Crunchbase, TechCrunch',
  '2025',
  '3',
  '7',
  'Unicorn ($1B+)',
  'True',
  '1'],
 ['Infinite Reality',
  '2025-08-01',
  'Growth Equity',
  '3000',
  '',
  '',
  'Private investor (undisclosed)',
  'None disclosed',
  'AI Application',
  'XR / Immersive AI',
  'Orlando',
  'United States',
  '2019',
  'Amish Shah',
  '500',
  '',
  'False',
  'Private',
  'XR, immersive commerce, AI media',
  'False',
  'Crunchbase',
  '2025',
  '3',
  '8',
  'Unicorn ($1B+)',
  'True',
  '7'],
 ['Anduril Industries',
  '2025-08-15',
  'Series F',
  '2500',
  '26500.0',
  '29000.0',
  'Founders Fund',
  'a16z, 8VC, General Catalyst, Lux Capital',
  'AI Application',
  'Defense AI',
  'Costa Mesa',
  'United States',
  '2017',
  'Palmer Luckey',
  '4500',
  '1000.0',
  'False',
  'Private',
  'Lattice, Ghost, ALTIUS, Menace',
  'False',
  'TechCrunch, Reuters',
  '2025',
  '3',
  '8',
  'Unicorn ($1B+)',
  'True',
  '7'],
 ['Anthropic',
  '2025-09-02',
  'Series F',
  '13000',
  '170000.0',
  '183000.0',
  'Iconiq Capital, Fidelity, Lightspeed',
  'BlackRock, Blackstone, Coatue, Qatar Investment Authority',
  'Foundation Model / LLM',
  'AI Safety Research',
  'San Francisco',
  'United States',
  '2021',
  'Dario Amodei',
  '1600',
  '4000.0',
  'False',
  'Private',
  'Claude, Claude API, Constitutional AI',
  'False',
  'TechCrunch, Crunchbase',
  '2025',
  '3',
  '9',
  'Mega ($10B+)',
  'True',
  '7'],
 ['Project Prometheus',
  '2025-11-01',
  'Seed / Launch',
  '6200',
  '',
  '',
  'Undisclosed',
  'Jeff Bezos (co-CEO)',
  'AI for Physical World',
  'Engineering / Manufacturing AI',
  'San Francisco',
  'United States',
  '2025',
  'Jeff Bezos, Vik Bajaj',
  '50',
  '',
  'False',
  'Private',
  'AI for physical economy',
  'False',
  'Crunchbase',
  '2025',
  '4',
  '11',
  'Unicorn ($1B+)',
  'True',
  '1'],
 ['Anysphere (Cursor)',
  '2025-11-13',
  'Series C',
  '2300',
  '27000.0',
  '29300.0',
  'Accel, Coatue',
  'Thrive Capital, DST Global, Google, Nvidia',
  'AI Application',
  'AI Coding Assistant',
  'San Francisco',
  'United States',
  '2022',
  'Michael Truell',
  '100',
  '500.0',
  'True',
  'Private',
  'Cursor AI IDE',
  'False',
  'TechCrunch, Bloomberg',
  '2025',
  '4',
  '11',
  'Unicorn ($1B+)',
  'True',
  '4'],
 ['Databricks',
  '2025-12-01',
  'Series J',
  '5000',
  '129000.0',
  '134000.0',
  'Thrive Capital',
  'a16z, DST Global, Insight Partners',
  'AI Infrastructure',
  'Data Platform / ML Infrastructure',
  'San Francisco',
  'United States',
  '2013',
  'Ali Ghodsi',
  '7000',
  '3500.0',
  'False',
  'Private (IPO expected 2026)',
  'Databricks Lakehouse, Mosaic ML, Unity Catalog',
  'True',
  'Bloomberg, TechCrunch',
  '2025',
  '4',
  '12',
  'Unicorn ($1B+)',
  'True',
  '10']]

In [31]:
import pandas as pd

df_aistartup_raw = pd.read_csv("data/ai_startup_funding_database_2014_2025.csv")
df_aistartup_raw.head()
df_aistartup_raw.tail()

,company,deal_date,round_type,amount_usd_millions,pre_money_valuation_millions,post_money_valuation_millions,lead_investors,other_investors,sector,subsector,...,ipo_status,key_products,open_source,source,year,quarter,month,deal_size_tier,is_us_company,stage_number
33,Anduril Industries,2025-08-15,Series F,2500,26500.0,29000.0,Founders Fund,"a16z, 8VC, General Catalyst, Lux Capital",AI Application,Defense AI,...,Private,"Lattice, Ghost, ALTIUS, Menace",False,"TechCrunch, Reuters",2025,3,8,Unicorn ($1B+),True,7
34,Anthropic,2025-09-02,Series F,13000,170000.0,183000.0,"Iconiq Capital, Fidelity, Lightspeed","BlackRock, Blackstone, Coatue, Qatar Investmen...",Foundation Model / LLM,AI Safety Research,...,Private,"Claude, Claude API, Constitutional AI",False,"TechCrunch, Crunchbase",2025,3,9,Mega ($10B+),True,7
35,Project Prometheus,2025-11-01,Seed / Launch,6200,NaN,NaN,Undisclosed,Jeff Bezos (co-CEO),AI for Physical World,Engineering / Manufacturing AI,...,Private,AI for physical economy,False,Crunchbase,2025,4,11,Unicorn ($1B+),True,1
36,Anysphere (Cursor),2025-11-13,Series C,2300,27000.0,29300.0,"Accel, Coatue","Thrive Capital, DST Global, Google, Nvidia",AI Application,AI Coding Assistant,...,Private,Cursor AI IDE,False,"TechCrunch, Bloomberg",2025,4,11,Unicorn ($1B+),True,4
37,Databricks,2025-12-01,Series J,5000,129000.0,134000.0,Thrive Capital,"a16z, DST Global, Insight Partners",AI Infrastructure,Data Platform / ML Infrastructure,...,Private (IPO expected 2026),"Databricks Lakehouse, Mosaic ML, Unity Catalog",True,"Bloomberg, TechCrunch",2025,4,12,Unicorn ($1B+),True,10

In [32]:

df_invest_raw = pd.read_csv("data/investments_VC.csv", encoding="latin1")
df_invest_raw.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,News,"17,50,000",acquired,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"40,00,000",operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Publishing,"40,000",operating,EST,NaN,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Electronics,"15,00,000",operating,GBR,NaN,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/r-ranch-and-mine,-R- Ranch and Mine,NaN,|Tourism|Entertainment|Games|,Tourism,"60,000",operating,USA,TX,Dallas,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
df_aistartup_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   company                        38 non-null     str
 1   deal_date                      38 non-null     str
 2   round_type                     38 non-null     str
 3   amount_usd_millions            38 non-null     int64
 4   pre_money_valuation_millions   28 non-null     float64
 5   post_money_valuation_millions  31 non-null     float64
 6   lead_investors                 38 non-null     str
 7   other_investors                36 non-null     str
 8   sector                         38 non-null     str
 9   subsector                      38 non-null     str
 10  hq_city                        38 non-null     str
 11  hq_country                     38 non-null     str
 12  founded_year                   38 non-null     int64
 13  ceo                            38 non-null     str
 14  employees_approx               38 non-null     int64
 15  annual_revenue_millions        25 non-null     float64
 16  profitable                     38 non-null     bool
 17  ipo_status                     38 non-null     str
 18  key_products                   38 non-null     str
 19  open_source                    38 non-null     bool
 20  source                         38 non-null     str
 21  year                           38 non-null     int64
 22  quarter                        38 non-null     int64
 23  month                          38 non-null     int64
 24  deal_size_tier                 38 non-null     str
 25  is_us_company                  38 non-null     bool
 26  stage_number                   38 non-null     int64
dtypes: bool(3), float64(3), int64(7), str(14)
memory usage: 15.8 KB

In [17]:
df_invest_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 54294 entries, 0 to 54293
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   permalink             49438 non-null  str
 1   name                  49437 non-null  str
 2   homepage_url          45989 non-null  str
 3   category_list         45477 non-null  str
 4    market               45470 non-null  str
 5    funding_total_usd    49438 non-null  str
 6   status                48124 non-null  str
 7   country_code          44165 non-null  str
 8   state_code            30161 non-null  str
 9   region                44165 non-null  str
 10  city                  43322 non-null  str
 11  funding_rounds        49438 non-null  float64
 12  founded_at            38554 non-null  str
 13  founded_month         38482 non-null  str
 14  founded_quarter       38482 non-null  str
 15  founded_year          38482 non-null  float64
 16  first_funding_at      49438 non-null  str
 17  last_funding_at       49438 non-null  str
 18  seed                  49438 non-null  float64
 19  venture               49438 non-null  float64
 20  equity_crowdfunding   49438 non-null  float64
 21  undisclosed           49438 non-null  float64
 22  convertible_note      49438 non-null  float64
 23  debt_financing        49438 non-null  float64
 24  angel                 49438 non-null  float64
 25  grant                 49438 non-null  float64
 26  private_equity        49438 non-null  float64
 27  post_ipo_equity       49438 non-null  float64
 28  post_ipo_debt         49438 non-null  float64
 29  secondary_market      49438 non-null  float64
 30  product_crowdfunding  49438 non-null  float64
 31  round_A               49438 non-null  float64
 32  round_B               49438 non-null  float64
 33  round_C               49438 non-null  float64
 34  round_D               49438 non-null  float64
 35  round_E               49438 non-null  float64
 36  round_F               49438 non-null  float64
 37  round_G               49438 non-null  float64
 38  round_H               49438 non-null  float64
dtypes: float64(23), str(16)
memory usage: 24.5 MB

In [10]:
df_aistartup_raw.describe()

,amount_usd_millions,pre_money_valuation_millions,post_money_valuation_millions,founded_year,employees_approx,annual_revenue_millions,year,quarter,month,stage_number
count,38.000000,28.000000,31.000000,38.000000,38.000000,25.00000,38.000000,38.000000,38.000000,38.000000
mean,4093.263158,45879.642857,48103.225806,2018.052632,1351.710526,1644.68000,2023.500000,2.473684,6.447368,5.210526
std,7083.857602,68054.906685,71243.135266,5.135712,1865.806932,2507.94527,2.226984,1.058731,3.374766,2.772041
min,0.000000,900.000000,1000.000000,2003.000000,30.000000,11.00000,2014.000000,1.000000,1.000000,0.000000
25%,500.000000,3948.750000,5250.000000,2015.000000,250.000000,150.00000,2023.000000,2.000000,4.000000,3.250000
50%,1670.000000,18250.000000,20000.000000,2019.000000,475.000000,850.00000,2024.000000,2.000000,6.000000,5.000000
75%,4750.000000,42250.000000,40400.000000,2022.000000,1375.000000,1900.00000,2025.000000,3.000000,9.000000,7.000000
max,40000.000000,260000.000000,300000.000000,2025.000000,7000.000000,11600.00000,2025.000000,4.000000,12.000000,10.000000

In [19]:
df_invest_raw.describe()

,funding_rounds,founded_year,seed,venture,equity_crowdfunding,undisclosed,convertible_note,debt_financing,angel,grant,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
count,49438.000000,38482.000000,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,...,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04,4.943800e+04
mean,1.696205,2007.359129,2.173215e+05,7.501051e+06,6.163322e+03,1.302213e+05,2.336410e+04,1.888157e+06,6.541898e+04,1.628453e+05,...,3.845592e+04,7.074227e+03,1.243955e+06,1.492891e+06,1.205356e+06,7.375261e+05,3.424682e+05,1.697692e+05,5.767067e+04,1.423197e+04
std,1.294213,7.579203,1.056985e+06,2.847112e+07,1.999048e+05,2.981404e+06,1.432046e+06,1.382046e+08,6.582908e+05,5.612088e+06,...,3.864461e+06,4.282166e+05,5.531974e+06,7.472704e+06,7.993592e+06,9.815218e+06,5.406915e+06,6.277905e+06,5.252312e+06,2.716865e+06
min,1.000000,1902.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000,2006.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000,2010.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.000000,2012.000000,2.500000e+04,5.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,18.000000,2014.000000,1.300000e+08,2.351000e+09,2.500000e+07,2.924328e+08,3.000000e+08,3.007950e+10,6.359026e+07,7.505000e+08,...,6.806116e+08,7.200000e+07,3.190000e+08,5.420000e+08,4.900000e+08,1.200000e+09,4.000000e+08,1.060000e+09,1.000000e+09,6.000000e+08

In [14]:
df_aistartup_raw.isna().sum()

company                           0
deal_date                         0
round_type                        0
amount_usd_millions               0
pre_money_valuation_millions     10
post_money_valuation_millions     7
lead_investors                    0
other_investors                   2
sector                            0
subsector                         0
hq_city                           0
hq_country                        0
founded_year                      0
ceo                               0
employees_approx                  0
annual_revenue_millions          13
profitable                        0
ipo_status                        0
key_products                      0
open_source                       0
source                            0
year                              0
quarter                           0
month                             0
deal_size_tier                    0
is_us_company                     0
stage_number                      0
dtype: int64

In [20]:
df_invest_raw.isna().sum()

permalink                4856
name                     4857
homepage_url             8305
category_list            8817
 market                  8824
 funding_total_usd       4856
status                   6170
country_code            10129
state_code              24133
region                  10129
city                    10972
funding_rounds           4856
founded_at              15740
founded_month           15812
founded_quarter         15812
founded_year            15812
first_funding_at         4856
last_funding_at          4856
seed                     4856
venture                  4856
equity_crowdfunding      4856
undisclosed              4856
convertible_note         4856
debt_financing           4856
angel                    4856
grant                    4856
private_equity           4856
post_ipo_equity          4856
post_ipo_debt            4856
secondary_market         4856
product_crowdfunding     4856
round_A                  4856
round_B                  4856
round_C                  4856
round_D                  4856
round_E                  4856
round_F                  4856
round_G                  4856
round_H                  4856
dtype: int64

In [ ]:
df_aistartup_raw.duplicated().sum()

np.int64(0)

In [22]:
df_invest_raw.duplicated().sum()

np.int64(4855)

In [25]:
df_invest_raw = df_invest_raw.drop_duplicates()

In [26]:
df_invest_raw.duplicated().sum()

np.int64(0)

In [27]:
df_aistartup_raw.dtypes

company                              str
deal_date                            str
round_type                           str
amount_usd_millions                int64
pre_money_valuation_millions     float64
post_money_valuation_millions    float64
lead_investors                       str
other_investors                      str
sector                               str
subsector                            str
hq_city                              str
hq_country                           str
founded_year                       int64
ceo                                  str
employees_approx                   int64
annual_revenue_millions          float64
profitable                          bool
ipo_status                           str
key_products                         str
open_source                         bool
source                               str
year                               int64
quarter                            int64
month                              int64
deal_size_tier                       str
is_us_company                       bool
stage_number                       int64
dtype: object

In [28]:
df_aistartup_raw['deal_date'] = pd.to_datetime(df_aistartup_raw['deal_date'])

In [29]:
df_aistartup_raw.dtypes

company                                     str
deal_date                        datetime64[us]
round_type                                  str
amount_usd_millions                       int64
pre_money_valuation_millions            float64
post_money_valuation_millions           float64
lead_investors                              str
other_investors                             str
sector                                      str
subsector                                   str
hq_city                                     str
hq_country                                  str
founded_year                              int64
ceo                                         str
employees_approx                          int64
annual_revenue_millions                 float64
profitable                                 bool
ipo_status                                  str
key_products                                str
open_source                                bool
source                                      str
year                                      int64
quarter                                   int64
month                                     int64
deal_size_tier                              str
is_us_company                              bool
stage_number                              int64
dtype: object

In [30]:
df_invest_raw.dtypes

permalink                   str
name                        str
homepage_url                str
category_list               str
 market                     str
 funding_total_usd          str
status                      str
country_code                str
state_code                  str
region                      str
city                        str
funding_rounds          float64
founded_at                  str
founded_month               str
founded_quarter             str
founded_year            float64
first_funding_at            str
last_funding_at             str
seed                    float64
venture                 float64
equity_crowdfunding     float64
undisclosed             float64
convertible_note        float64
debt_financing          float64
angel                   float64
grant                   float64
private_equity          float64
post_ipo_equity         float64
post_ipo_debt           float64
secondary_market        float64
product_crowdfunding    float64
round_A                 float64
round_B                 float64
round_C                 float64
round_D                 float64
round_E                 float64
round_F                 float64
round_G                 float64
round_H                 float64
dtype: object

In [34]:
df_invest_raw.columns = df_invest_raw.columns.str.strip()

In [35]:
df_invest_raw["founded_at"] = pd.to_datetime(df_invest_raw["founded_at"], errors="coerce")

df_invest_raw["first_funding_at"] = pd.to_datetime(df_invest_raw["first_funding_at"], errors="coerce")

df_invest_raw["last_funding_at"] = pd.to_datetime(df_invest_raw["last_funding_at"], errors="coerce")

df_invest_raw["funding_total_usd"] = pd.to_numeric(
    df_invest_raw["funding_total_usd"]
    .str.replace(",", "", regex=False),
    errors="coerce"
)

In [36]:
df_invest_raw.dtypes

permalink                          str
name                               str
homepage_url                       str
category_list                      str
market                             str
funding_total_usd              float64
status                             str
country_code                       str
state_code                         str
region                             str
city                               str
funding_rounds                 float64
founded_at              datetime64[us]
founded_month                      str
founded_quarter                    str
founded_year                   float64
first_funding_at        datetime64[us]
last_funding_at         datetime64[us]
seed                           float64
venture                        float64
equity_crowdfunding            float64
undisclosed                    float64
convertible_note               float64
debt_financing                 float64
angel                          float64
grant                          float64
private_equity                 float64
post_ipo_equity                float64
post_ipo_debt                  float64
secondary_market               float64
product_crowdfunding           float64
round_A                        float64
round_B                        float64
round_C                        float64
round_D                        float64
round_E                        float64
round_F                        float64
round_G                        float64
round_H                        float64
dtype: object

In [66]:
df_invest_raw["founded_year"] = pd.to_numeric(df_invest_raw["founded_year"], errors="coerce").astype("Int64")
df_invest_raw["founded_month"] = pd.to_datetime(df_invest_raw["founded_month"], format="%Y-%m", errors="coerce")

In [67]:
df_invest_raw.dtypes

permalink                          str
name                               str
homepage_url                       str
category_list                      str
market                             str
funding_total_usd              float64
status                             str
country_code                       str
state_code                         str
region                             str
city                               str
funding_rounds                 float64
founded_at              datetime64[us]
founded_month           datetime64[us]
founded_quarter                    str
founded_year                     Int64
first_funding_at        datetime64[us]
last_funding_at         datetime64[us]
seed                           float64
venture                        float64
equity_crowdfunding            float64
undisclosed                    float64
convertible_note               float64
debt_financing                 float64
angel                          float64
grant                          float64
private_equity                 float64
post_ipo_equity                float64
post_ipo_debt                  float64
secondary_market               float64
product_crowdfunding           float64
round_A                        float64
round_B                        float64
round_C                        float64
round_D                        float64
round_E                        float64
round_F                        float64
round_G                        float64
round_H                        float64
dtype: object

In [74]:
df_invest_raw[
    df_invest_raw["market"].str.contains("Artificial Intelligence|Machine Learning|Deep Learning|Generative AI", case=False, na=False) |
    df_invest_raw["category_list"].str.contains("Artificial Intelligence|Machine Learning|Deep Learning|Generative AI", case=False, na=False)
]

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
179,/organization/gazaro,360pi,http://www.360pi.com,|Semantic Web|Artificial Intelligence|Shopping...,Artificial Intelligence,4100000.0,operating,CAN,ON,Ottawa,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
186,/organization/365looks,365looks,http://365looks.com,|Artificial Intelligence|Technology|Fashion|,Fashion,73047.0,operating,ESP,NaN,ESP - Other,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,/organization/405labs,405Labs,http://www.405labs.com/,|Machine Learning|Network Security|,Machine Learning,81000.0,operating,USA,CA,San Diego,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1180,/organization/adstage,AdStage,https://www.adstage.io,|Sales and Marketing|SEO|Internet|Software|Ent...,Software,8750000.0,operating,USA,CA,SF Bay Area,...,0.0,0.0,6250000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1187,/organization/adtelligence,ADTELLIGENCE,http://www.adtelligence.de,|Customer Service|Reviews and Recommendations|...,Machine Learning,NaN,operating,DEU,NaN,Frankfurt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47743,/organization/wiseri,wiseri,http://www.wiseri.com,|Gamification|Recruiting|Crowdsourcing|Artific...,Gamification,163524.0,operating,ESP,NaN,San Sebastián De Los Reyes,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48316,/organization/xplr,Xplr Software,http://xplr.com,|Data Visualization|Machine Learning|Big Data|...,Data Visualization,150000.0,operating,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48563,/organization/ylopo,Ylopo,http://www.ylopo.com/,|Machine Learning|Marketing Automation|,Marketing Automation,NaN,operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48604,/organization/yones,Yones,http://www.yones.net,|Publishing|Machine Learning|Reviews and Recom...,News,125000.0,operating,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48901,/organization/zauber,Zauber,http://www.zauberlabs.com,|Opinions|Social Television|Mobile|Semantic We...,Software,1000000.0,operating,ARG,NaN,Buenos Aires,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
print("Artificial Intelligence:", df_invest_raw["category_list"].str.contains("Artificial Intelligence", case=False, na=False).sum())

print("Machine Learning:", df_invest_raw["category_list"].str.contains("Machine Learning", case=False, na=False).sum())

print("Deep Learning:", df_invest_raw["category_list"].str.contains("Deep Learning", case=False, na=False).sum())

print("Generative AI:", df_invest_raw["category_list"].str.contains("Generative AI", case=False, na=False).sum())

print("Natural Language Processing:", df_invest_raw["category_list"].str.contains("Natural Language Processing", case=False, na=False).sum())

print("AI:", df_invest_raw["category_list"].str.contains(r"\bAI\b", case=False, na=False).sum())

Artificial Intelligence: 100
Machine Learning: 112
Deep Learning: 0
Generative AI: 0
Natural Language Processing: 42
AI: 0

In [87]:
df_invest_ai = df_invest_raw[
    df_invest_raw["category_list"].str.contains(
        "Artificial Intelligence|Machine Learning|Natural Language Processing",
        case=False,
        na=False
    )
]

In [88]:
df_invest_ai["name"].nunique()

219

In [89]:
df_invest_ai

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
179,/organization/gazaro,360pi,http://www.360pi.com,|Semantic Web|Artificial Intelligence|Shopping...,Artificial Intelligence,4100000.0,operating,CAN,ON,Ottawa,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
186,/organization/365looks,365looks,http://365looks.com,|Artificial Intelligence|Technology|Fashion|,Fashion,73047.0,operating,ESP,NaN,ESP - Other,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
267,/organization/405labs,405Labs,http://www.405labs.com/,|Machine Learning|Network Security|,Machine Learning,81000.0,operating,USA,CA,San Diego,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1180,/organization/adstage,AdStage,https://www.adstage.io,|Sales and Marketing|SEO|Internet|Software|Ent...,Software,8750000.0,operating,USA,CA,SF Bay Area,...,0.0,0.0,6250000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1187,/organization/adtelligence,ADTELLIGENCE,http://www.adtelligence.de,|Customer Service|Reviews and Recommendations|...,Machine Learning,NaN,operating,DEU,NaN,Frankfurt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47743,/organization/wiseri,wiseri,http://www.wiseri.com,|Gamification|Recruiting|Crowdsourcing|Artific...,Gamification,163524.0,operating,ESP,NaN,San Sebastián De Los Reyes,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48316,/organization/xplr,Xplr Software,http://xplr.com,|Data Visualization|Machine Learning|Big Data|...,Data Visualization,150000.0,operating,USA,NY,New York City,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48563,/organization/ylopo,Ylopo,http://www.ylopo.com/,|Machine Learning|Marketing Automation|,Marketing Automation,NaN,operating,USA,CA,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48604,/organization/yones,Yones,http://www.yones.net,|Publishing|Machine Learning|Reviews and Recom...,News,125000.0,operating,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48901,/organization/zauber,Zauber,http://www.zauberlabs.com,|Opinions|Social Television|Mobile|Semantic We...,Software,1000000.0,operating,ARG,NaN,Buenos Aires,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
df_aistartup_raw

,company,deal_date,round_type,amount_usd_millions,pre_money_valuation_millions,post_money_valuation_millions,lead_investors,other_investors,sector,subsector,...,ipo_status,key_products,open_source,source,year,quarter,month,deal_size_tier,is_us_company,stage_number
0,DeepMind,2014-01-26,Acquisition,500,NaN,NaN,Google (acquirer),NaN,Foundation Model / Research,AI Research Lab,...,Acquired by Google,"AlphaFold, Gemini, AlphaGo",True,"The Information, Google",2014,1,1,Large ($500M+),False,0
1,OpenAI,2019-07-22,Strategic Investment,1000,NaN,NaN,Microsoft,None disclosed,Foundation Model / LLM,General-Purpose AI,...,Private,"GPT-2, OpenAI Five",True,Microsoft blog,2019,3,7,Unicorn ($1B+),True,8
2,Palantir,2020-09-30,Direct Listing,0,NaN,15800.0,Public Market (NYSE),NaN,AI Application,Data Analytics / Defense AI,...,Public (NYSE: PLTR),"Foundry, Gotham, AIP",False,SEC filing,2020,3,9,Early (<$100M),True,10
3,UiPath,2021-04-21,IPO,1340,NaN,35800.0,Public Market (NYSE),"Morgan Stanley, JPMorgan, BofA",AI Application,Robotic Process Automation,...,Public (NYSE: PATH),"UiPath Platform, AI Center",False,SEC S-1 filing,2021,2,4,Unicorn ($1B+),True,10
4,SenseTime,2021-12-20,IPO,740,NaN,16800.0,Public Market (HKEX),"Cornerstone: CITIC, CICC, HAO Capital",AI Application,Computer Vision / Smart City,...,Public (HKEX: 0020),"SenseCore, facial recognition, autonomous driving",False,HKEX filings,2021,4,12,Large ($500M+),False,10
5,OpenAI,2022-04-01,Series D,300,19700.0,20000.0,"Tiger Global, a16z","Sequoia Capital, Bedrock",Foundation Model / LLM,General-Purpose AI,...,Private,"GPT-3, DALL-E 2, Codex",False,"WSJ, PitchBook",2022,2,4,Growth ($100M+),True,5
6,Adept AI,2022-04-26,Series A,65,935.0,1000.0,Greylock Partners,"Addition, Atlassian Ventures",AI Application,AI Agent / Action Models,...,Acqui-hired by Amazon 2024,ACT-1 action model,False,"TechCrunch, The Information",2022,2,4,Early (<$100M),True,2
7,Stability AI,2022-10-17,Seed,101,900.0,1000.0,"Lightspeed, Coatue",O'Shaughnessy Ventures,Foundation Model / Image Gen,Image Generation,...,Private (struggling),Stable Diffusion,True,"Bloomberg, TechCrunch",2022,4,10,Growth ($100M+),False,1
8,OpenAI,2023-01-23,Strategic Investment,10000,19000.0,29000.0,Microsoft,None disclosed,Foundation Model / LLM,General-Purpose AI,...,Private,"ChatGPT, GPT-4, DALL-E 2",False,"Microsoft blog, WSJ",2023,1,1,Mega ($10B+),True,8
9,Cohere,2023-06-08,Series C,270,1930.0,2200.0,Inovia Capital,"Nvidia, Oracle, Salesforce Ventures, Index Ven...",Foundation Model / LLM,Enterprise AI,...,Private,"Command, Embed, Rerank",True,TechCrunch,2023,2,6,Growth ($100M+),False,4
10,Inflection AI,2023-06-29,Series B,1300,2700.0,4000.0,"Microsoft, Nvidia, Reid Hoffman","Bill Gates, Eric Schmidt, Greylock",Foundation Model / LLM,Personal AI Assistant,...,Effectively Acquired by Microsoft,Pi personal AI (wound down),False,"NYT, Bloomberg",2023,2,6,Unicorn ($1B+),True,3
11,Hugging Face,2023-08-24,Series D,235,4265.0,4500.0,"Google, Amazon, Nvidia","Salesforce, AMD, Intel, IBM, Qualcomm",AI Infrastructure,Open Source AI Platform,...,Private,"Hugging Face Hub, Transformers, Inference API",True,"TechCrunch, Hugging Face blog",2023,3,8,Growth ($100M+),True,5
12,Anthropic,2023-09-25,Strategic Investment,4000,NaN,NaN,Amazon,None disclosed,Foundation Model / LLM,AI Safety Research,...,Private,"Claude 2, Claude API",False,"Amazon press release, WSJ",2023,3,9,Unicorn ($1B+),True,8
13,Figure AI,2024-02-29,Series B,675,2000.0,2600.0,"Microsoft, Nvidia, OpenAI Startup Fund","Jeff Bezos, Intel, Samsung, Parkway Venture Ca...",AI Application,Humanoid Robotics,...,Private,"Figure 01, Figure 02 humanoid robots",False,"Bloomberg, TechCrunch",2024,1,2,Large ($500M+),True,3
14,Anthropic,2024-03-01,Series D,2750,15250.0,18400.0,Menlo Ventures,"Google, Spark Capital, Salesforce Ventures",Foundation Model / LLM,AI Safety Research,...,Private,"Claude 3, Claude API",False,"TechCrunch, SEC filing",2024,1,3,Unicorn ($1B+),True,5
15,Wayve,2024-05-07,Series C,1050,NaN,NaN,SoftBank Vision Fund,"Nvidia, Microsoft, Eclipse Ventures",AI Application,Autonomous Driving,...,Private,"LINGO-2, AI driving platform",False,"TechCrunch, Financial Times",2024,2,5,Unicorn ($1B+),False,4
16,Mistral AI,2024-06-11,Series B,640,5400.0,6000.0,General Catalyst,"a16z, Lightspeed, BNP Paribas, Samsung",Foundation Model / LLM,Open-Weight AI Models,...,Private,"Mistral Large, Mixtral, Le Chat",True,"TechCrunch, Les Echos",2024,2,6,Large ($500M+),False,3
17,Databricks,2024-09-19,Series I,10000,52000.0,62000.0,Thrive Capital,"a16z, DST Global, GIC, Iconiq",AI Infrastructure,Data Platform / ML Infrastructure,...,Private,"Databricks Lakehouse, Mosaic ML",True,Bloomberg,2024,3,9,Mega ($10B+),True,9
18,OpenAI,2024-10-02,Series E,6600,150000.0,157000.0,Thrive Capital,"Microsoft, Nvidia, SoftBank, Khosla Ventures, ...",Foundation Model / LLM,General-Purpose AI,...,Private,"ChatGPT, GPT-4, DALL-E 3, Sora",False,"SEC filing, TechCrunch",2024,4,10,Unicorn ($1B+),True,6
19,CoreWeave,2024-11-21,Series C,650,22350.0,23000.0,Jane Street Capital,"Fidelity, Coatue, Magnetar",AI Infrastructure,GPU Cloud Computing,...,IPO March 2025 (CRWV),"GPU cloud, AI training clusters",False,"Bloomberg, Crunchbase",2024,4,11,Large ($500M+),True,4
20,xAI,2024-12-23,Series C,6000,39000.0,45000.0,Various (undisclosed),"Nvidia, A-Cap, Valor Equity Partners",Foundation Model / LLM,General-Purpose AI,...,Private,"Grok 2, Colossus",True,"Bloomberg, SEC filing",2024,4,12,Unicorn ($1B+),True,4
21,Mistral AI,2025-01-27,Series C,2000,13500.0,15500.0,"General Catalyst, Bpifrance","a16z, Lightspeed, Samsung, IBM",Foundation Model / LLM,Open-Weight AI Models,...,Private,"Mistral Large 2, Codestral, Le Chat",True,"TechCrunch, Les Echos",2025,1,1,Unicorn ($1B+),False,4
22,Lambda,2025-02-19,Series D,480,2000.0,2500.0,"SGW, Andra Capital","Nvidia, G Squared, ARK Invest",AI Infrastructure,GPU Cloud Computing,...,Private,"Lambda Cloud, GPU clusters",False,TechCrunch,2025,1,2,Growth ($100M+),True,5
23,Together AI,2025-02-20,Series B,305,3000.0,3300.0,"Prosperity7, General Catalyst","Salesforce Ventures, Nvidia, Lux Capital",AI Infrastructure,Open Source AI Platform,...,Private,"Together Inference, Together Fine-Tuning",True,TechCrunch,2025,1,2,Growth ($100M+),True,3
24,Anthropic,2025-03-03,Series E Extension,3500,58000.0,61500.0,Lightspeed Venture Partners,"Salesforce Ventures, Menlo Ventures, General C...",Foundation Model / LLM,AI Safety Research,...,Private,"Claude, Claude API",False,TechCrunch,2025,1,3,Unicorn ($1B+),True,6
25,Safe Superintelligence (SSI),2025-04-01,Series A,2000,30000.0,32000.0,Greenoaks Capital Partners,"a16z, Sequoia, DST Global",Foundation Model / LLM,AI Safety Research,...,Private,Safe superintelligence (stealth),False,"Bloomberg, Crunchbase",2025,2,4,Unicorn ($1B+),True,2
26,OpenAI,2025-04-02,Series F,40000,260000.0,300000.0,SoftBank,"Microsoft, Coatue, Thrive Capital",Foundation Model / LLM,General-Purpose AI,...,Private (IPO rumored),"ChatGPT, GPT-4o, DALL-E, Sora",False,"CNBC, Reuters, Crunchbase",2025,2,4,Mega ($10B+),True,7
27,Perplexity AI,2025-05-01,Series E,500,17500.0,18000.0,Accel,"IVP, Nvidia, Bezos Expeditions",AI Application,AI Search Engine,...,Private,"Perplexity Search, Perplexity Pro",False,"Forbes, TechCrunch",2025,2,5,Large ($500M+),True,6
28,Ambience Healthcare,2025-06-01,Series C,243,NaN,NaN,"Oak HC/FT, a16z","Kleiner Perkins, OpenAI Startup Fund",AI Application,Healthcare AI,...,Private,"AI medical documentation, clinical AI OS",False,TechCrunch,2025,2,6,Growth ($100M+),True,4
29,Scale AI,2025-06-15,Strategic Investment,14300,14700.0,29000.0,Meta (49% stake),None disclosed,AI Infrastructure,Data Labeling / Training Data,...,Private,"Data labeling, RLHF, AI infrastructure",False,"Bloomberg, TechCrunch",2025,2,6,Mega ($10B+),True,8
30,xAI,2025-07-15,Series C,10000,190000.0,200000.0,"Valor Capital, Qatar Investment Authority","Kingdom Holding (Prince Al Waleed), Nvidia",Foundation Model / LLM,General-Purpose AI,...,Private,"Grok, Grok 4, Colossus supercomputer",True,Bloomberg (Musk disputes figures),2025,3,7,Mega ($10B+),True,4
31,Thinking Machines Lab,2025-07-15,Seed,2000,8000.0,10000.0,Andreessen Horowitz,"Nvidia, Accel, AMD, Cisco",Foundation Model / LLM,AI Research,...,Private,Foundation models (stealth),False,"Crunchbase, TechCrunch",2025,3,7,Unicorn ($1B+),True,1
32,Infinite Reality,2025-08-01,Growth Equity,3000,NaN,NaN,Private investor (undisclosed),None disclosed,AI Application,XR / Immersive AI,...,Private,"XR, immersive commerce, AI media",False,Crunchbase,2025,3,8,Unicorn ($1B+),True,7
33,Anduril Industries,2025-08-15,Series F,2500,26500.0,29000.0,Founders Fund,"a16z, 8VC, General Catalyst, Lux Capital",AI Application,Defense AI,...,Private,"Lattice, Ghost, ALTIUS, Menace",False,"TechCrunch, Reuters",2025,3,8,Unicorn ($1B+),True,7
34,Anthropic,2025-09-02,Series F,13000,170000.0,183000.0,"Iconiq Capital, Fidelity, Lightspeed","BlackRock, Blackstone, Coatue, Qatar Investmen...",Foundation Model / LLM,AI Safety Research,...,Private,"Claude, Claude API, Constitutional AI",False,"TechCrunch, Crunchbase",2025,3,9,Mega ($10B+),True,7
35,Project Prometheus,2025-11-01,Seed / Launch,6200,NaN,NaN,Undisclosed,Jeff Bezos (co-CEO),AI for Physical World,Engineering / Manufacturing AI,...,Private,AI for physical economy,False,Crunchbase,2025,4,11,Unicorn ($1B+),True,1
36,Anysphere (Cursor),2025-11-13,Series C,2300,27000.0,29300.0,"Accel, Coatue","Thrive Capital, DST Global, Google, Nvidia",AI Application,AI Coding Assistant,...,Private,Cursor AI IDE,False,"TechCrunch, Bloomberg",2025,4,11,Unicorn ($1B+),True,4
37,Databricks,2025-12-01,Series J,5000,129000.0,134000.0,Thrive Capital,"a16z, DST Global, Insight Partners",AI Infrastructure,Data Platform / ML Infrastructure,...,Private (IPO expected 2026),"Databricks Lakehouse, Mosaic ML, Unity Catalog",True,"Bloomberg, TechCrunch",2025,4,12,Unicorn ($1B+),True,10

In [96]:
df_aistartup_raw[df_aistartup_raw["company"] == "OpenAI"]

,company,deal_date,round_type,amount_usd_millions,pre_money_valuation_millions,post_money_valuation_millions,lead_investors,other_investors,sector,subsector,...,ipo_status,key_products,open_source,source,year,quarter,month,deal_size_tier,is_us_company,stage_number
1,OpenAI,2019-07-22,Strategic Investment,1000,NaN,NaN,Microsoft,None disclosed,Foundation Model / LLM,General-Purpose AI,...,Private,"GPT-2, OpenAI Five",True,Microsoft blog,2019,3,7,Unicorn ($1B+),True,8
5,OpenAI,2022-04-01,Series D,300,19700.0,20000.0,"Tiger Global, a16z","Sequoia Capital, Bedrock",Foundation Model / LLM,General-Purpose AI,...,Private,"GPT-3, DALL-E 2, Codex",False,"WSJ, PitchBook",2022,2,4,Growth ($100M+),True,5
8,OpenAI,2023-01-23,Strategic Investment,10000,19000.0,29000.0,Microsoft,None disclosed,Foundation Model / LLM,General-Purpose AI,...,Private,"ChatGPT, GPT-4, DALL-E 2",False,"Microsoft blog, WSJ",2023,1,1,Mega ($10B+),True,8
18,OpenAI,2024-10-02,Series E,6600,150000.0,157000.0,Thrive Capital,"Microsoft, Nvidia, SoftBank, Khosla Ventures, ...",Foundation Model / LLM,General-Purpose AI,...,Private,"ChatGPT, GPT-4, DALL-E 3, Sora",False,"SEC filing, TechCrunch",2024,4,10,Unicorn ($1B+),True,6
26,OpenAI,2025-04-02,Series F,40000,260000.0,300000.0,SoftBank,"Microsoft, Coatue, Thrive Capital",Foundation Model / LLM,General-Purpose AI,...,Private (IPO rumored),"ChatGPT, GPT-4o, DALL-E, Sora",False,"CNBC, Reuters, Crunchbase",2025,2,4,Mega ($10B+),True,7

In [99]:
df_invest_ai.drop(columns=["permalink", "homepage_url"], inplace=True)

In [97]:
df_aistartup_raw.to_csv("df_aistartups.csv", index=False)

In [100]:
df_invest_ai.to_csv("df_invest_ai.csv", index=False)